CREATE TABLE `Answer` (
	`AnswerID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`AnswerText`	TEXT NOT NULL,
	`Score`	INTEGER NOT NULL,
	`QuestionID`	INTEGER NOT NULL
);

PRAGMA foreign_keys = "1";
SELECT type,name,sql,tbl_name,'0' AS temp FROM sqlite_master UNION SELECT type,name,sql,tbl_name,'1' AS temp FROM sqlite_temp_master;
PRAGMA encoding
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Answer` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Answer` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Answer` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Answer` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `UserAnswer` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `UserAnswer` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `UserAnswer` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `UserAnswer` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Answer` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Answer` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Answer` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Answer` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Staff` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Staff` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Staff` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Staff` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Survey` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Survey` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Survey` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Survey` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `UserAnswer` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `UserAnswer` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `UserAnswer` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `UserAnswer` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Answer` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Answer` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Answer` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Answer` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='27';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (28,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='28';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='28';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='28';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (29,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='29';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='29';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='29';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (30,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='30';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='30';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='30';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (31,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='31';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='31';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='31';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (32,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='32';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='32';
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Answer` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Answer` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Answer` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Answer` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (33,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='33';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='33';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (34,'',0,0);
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='34';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='34';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='34';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (35,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='35';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='35';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='35';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (36,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='36';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='36';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='36';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (37,'',0,0);
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='37';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='37';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='37';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (38,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='38';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='38';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='38';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (39,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='39';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='39';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='39';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (40,'',0,0);
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Answer` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Answer` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Answer` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Answer` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='40';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='40';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='40';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (41,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='41';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (42,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='42';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (43,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='43';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (44,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='44';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (45,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='45';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='1';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='1';
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `UserAnswer` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `UserAnswer` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `UserAnswer` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `UserAnswer` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Survey` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Survey` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Survey` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Survey` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Patient` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Patient` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Patient` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Patient` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Staff` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Staff` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Staff` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Staff` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Staff` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Staff` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Staff` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Staff` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Answer` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Answer` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Answer` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Answer` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='41';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='42';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='43';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='44';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='45';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (46,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='46';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='46';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='45';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='44';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='43';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='42';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='41';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='46';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (47,'',0,0);
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='47';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (48,'',0,0);
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='48';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='47';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='48';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (49,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='48';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='47';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='49';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='49';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='49';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (50,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='50';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='50';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (51,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='51';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='51';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='51';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (52,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='52';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (53,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='53';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='52';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='53';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (54,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='54';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (55,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='55';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (56,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='56';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (57,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='57';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (58,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='58';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (59,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='59';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (60,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='60';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (61,'',0,0);
UPDATE `Answer` SET `Score`=? WHERE _rowid_='61';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='60';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='59';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='58';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='57';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='56';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='55';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='54';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='52';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='53';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='53';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='54';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='54';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='55';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='56';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='56';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='57';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='57';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='58';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='59';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='59';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='60';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='61';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='54';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='55';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='56';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='57';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='58';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='59';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='60';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='61';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='61';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (62,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='62';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='62';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='62';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (63,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='63';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='63';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='63';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (64,'',0,0);
UPDATE `Answer` SET `Score`=? WHERE _rowid_='64';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='64';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='64';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (65,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='65';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='65';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (66,'',0,0);
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (67,'',0,0);
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='65';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='66';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='67';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='65';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='66';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='67';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='66';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='66';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='67';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='66';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='67';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (68,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='68';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (69,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='69';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (70,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='70';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='69';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='70';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='68';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='69';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='70';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='69';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='70';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (71,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='71';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (72,'',0,0);
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (73,'',0,0);
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (74,'',0,0);
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (75,'',0,0);
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (76,'',0,0);
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (77,'',0,0);
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (78,'',0,0);
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (79,'',0,0);
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (80,'',0,0);
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (81,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='72';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='73';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='74';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='75';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='76';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='77';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='78';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='79';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='80';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='81';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='81';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='71';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='71';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='71';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='72';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='73';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='73';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='73';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='74';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='75';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='75';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='75';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='76';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='77';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='78';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='78';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='78';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='79';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='80';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='80';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='80';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='81';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='72';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='73';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='74';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='75';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='76';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='77';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='78';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='79';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='80';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='81';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (82,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='82';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (83,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='83';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (84,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='84';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='83';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='84';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='82';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='83';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='84';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='83';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='84';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (85,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='85';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (86,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='86';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (87,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='87';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (88,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='88';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (89,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='89';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (90,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='90';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (91,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='91';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (92,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='92';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='91';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='92';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='85';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='85';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='85';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='86';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='87';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='87';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='88';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='88';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='88';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='89';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='90';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='90';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='91';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='91';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='91';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='92';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='86';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='87';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='88';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='89';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='90';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='91';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='92';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (93,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='93';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (94,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='94';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (95,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='95';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (96,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='96';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (97,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='97';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (98,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='98';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (99,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='99';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (100,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='100';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='100';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='99';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='93';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='93';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='93';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='94';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='95';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='96';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='97';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='98';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='98';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='98';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='99';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='100';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='96';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='96';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='97';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='98';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='99';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='100';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (101,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='101';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (102,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='102';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (103,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='103';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (104,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='104';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='103';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='104';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='102';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='103';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='104';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='104';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='101';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='102';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='103';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='104';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='104';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (105,'',0,0);
UPDATE `Answer` SET `Score`=? WHERE _rowid_='105';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='105';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (106,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='106';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (107,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='107';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='107';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (108,'',0,0);
UPDATE `Answer` SET `Score`=? WHERE _rowid_='108';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='108';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='104';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='104';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='104';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='105';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='105';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='105';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='106';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='107';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='107';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='107';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='108';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='105';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='106';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='107';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='108';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (109,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='109';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (110,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='110';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (111,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='111';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='109';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='111';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='109';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='110';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='111';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (112,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='112';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (113,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='113';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (114,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='114';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (115,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='115';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (116,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='116';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (117,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='117';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (118,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='118';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (119,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='119';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (120,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='120';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (121,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='121';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='112';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='113';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='114';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='115';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='116';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='117';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='118';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='119';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='120';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='121';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='112';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='113';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='114';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='115';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='116';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='117';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='118';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='119';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='120';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='121';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='112';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='113';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='114';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='115';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='116';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='117';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='118';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='119';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='120';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='121';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (122,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='122';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (123,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='123';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (124,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='124';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='122';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='123';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='124';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='113';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='114';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='115';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='116';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='117';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='118';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='119';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='120';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='121';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='122';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='123';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='124';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (125,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='125';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (126,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='126';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (127,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='4';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='4';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='126';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='126';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='127';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='127';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (128,'',0,0);
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (129,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='126';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='127';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='128';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='129';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='125';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='125';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='126';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='126';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='126';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='127';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='127';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='128';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='129';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='128';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='128';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='129';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (130,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='130';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (131,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='4';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='131';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (132,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='5';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='5';
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='132';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='131';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='132';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='130';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='131';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='132';
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Answer` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Answer` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Answer` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Answer` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `UserAnswer` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `UserAnswer` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `UserAnswer` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `UserAnswer` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
CREATE TABLE `sqlitebrowser_rename_column_new_table` (
	`Question ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`QuestionText`	TEXT NOT NULL
);
INSERT INTO sqlitebrowser_rename_column_new_table SELECT `Question ID`,`Description` FROM `Question`;
PRAGMA defer_foreign_keys
PRAGMA defer_foreign_keys = "1";
DROP TABLE `Question`;
ALTER TABLE `sqlitebrowser_rename_column_new_table` RENAME TO `Question`
PRAGMA defer_foreign_keys = "0";
SELECT type,name,sql,tbl_name,'0' AS temp FROM sqlite_master UNION SELECT type,name,sql,tbl_name,'1' AS temp FROM sqlite_temp_master;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
PRAGMA auto_vacuum
PRAGMA automatic_index
PRAGMA checkpoint_fullfsync
PRAGMA foreign_keys
PRAGMA fullfsync
PRAGMA ignore_check_constraints
PRAGMA journal_mode
PRAGMA journal_size_limit
PRAGMA locking_mode
PRAGMA max_page_count
PRAGMA page_size
PRAGMA recursive_triggers
PRAGMA secure_delete
PRAGMA synchronous
PRAGMA temp_store
PRAGMA user_version
PRAGMA wal_autocheckpoint
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Question` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Answer` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Answer` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Answer` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Answer` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (133,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='133';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (134,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='134';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='133';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='134';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (135,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='135';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='133';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='134';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='135';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (136,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='136';
UPDATE `Answer` SET `Score`=? WHERE _rowid_='136';
UPDATE `Answer` SET `AnswerText`=? WHERE _rowid_='136';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (137,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='137';
INSERT INTO `Answer`(`AnswerID`,`AnswerText`,`Score`,`QuestionID`) VALUES (138,'',0,0);
UPDATE `Answer` SET `QuestionID`=? WHERE _rowid_='138';
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `UserAnswer` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `UserAnswer` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `UserAnswer` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `UserAnswer` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Survey` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Survey` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Survey` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Survey` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Answer` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Answer` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Answer` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Answer` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
